workflows:
  ios-swift-workflow:
    name: iOS Swift Workflow
    environment:
      xcode: 16.0
      vars:
        BUNDLE_ID: "simogatti.BetBox"
    scripts:
      - name: Build and Archive iOS app
        script: |
          cd iOS_APP
          xcodebuild clean archive -project BetBox.xcodeproj -scheme BetBox -archivePath BetBox.xcarchive
      - name: Export IPA
        script: |
          cd iOS_APP
          xcodebuild -exportArchive -archivePath BetBox.xcarchive -exportOptionsPlist exportOptions.plist -exportPath ./
    artifacts:
      - iOS_APP/BetBox.ipa
