workflows:
  ios-swift-workflow:
    name: iOS Swift Workflow
    environment:
      xcode: 16.0-beta
    scripts:
      - name: Build iOS app
        script: |
          cd iOS_APP
          xcodebuild build -project BetBox.xcodeproj -scheme BetBox -sdk iphonesimulator -configuration Release
    artifacts:
      - iOS_APP/build/ios/iphoneos/*.app
