workflows:
  ios-swift-workflow:
    name: iOS Swift Workflow
    environment:
      xcode: 16.0
    scripts:
      - name: Build iOS app
        script: |
          cd iOS_APP
          xcodebuild build -project BetBox.xcodeproj -scheme BetBox -sdk iphoneos -configuration Release
      - name: Export IPA
        script: |
          cd iOS_APP
          xcodebuild -exportArchive -archivePath build/BetBox.xcarchive -exportOptionsPlist exportOptions.plist -exportPath ./
    artifacts:
      - iOS_APP/BetBox.ipa
