workflows:
  ios-swift-workflow:
    name: iOS Swift Workflow
    environment:
      xcode: latest
    scripts:
      - name: Build iOS app
        script: |
          xcodebuild build -project BetBox.xcodeproj -scheme BetBox -sdk iphonesimulator -configuration Release
    artifacts:
      - build/ios/iphoneos/*.app