workflows:
  ios-swift-workflow:
    name: iOS Swift Workflow
    environment:
      xcode: 16.0
      vars:
        BUNDLE_ID: "simogatti.BetBox"
    scripts:
      - name: Build iOS app
        script: |
          cd iOS_APP
          xcodebuild build -project BetBox.xcodeproj -scheme BetBox -sdk iphonesimulator18.0 -configuration Debug
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
