workflows:
  ios-swift-workflow:
    name: iOS Swift Workflow
    environment:
      xcode: 16.0
      vars:
        BUNDLE_ID: "simogatti.BetBox"
    scripts:
      - name: Install Fastlane
        script: |
          cd iOS_APP
          gem install fastlane
      - name: Create Fastfile
        script: |
          cd iOS_APP
          cat > Fastfile << EOL
          default_platform(:ios)
          
          platform :ios do
            desc "Build IPA"
            lane :build_ipa do
              gym(
                project: "BetBox.xcodeproj",
                scheme: "BetBox",
                export_method: "development",
                output_directory: "./build",
                output_name: "BetBox.ipa",
                silent: true,
                suppress_xcode_output: true
              )
            end
          end
          EOL
      - name: Build IPA
        script: |
          cd iOS_APP
          fastlane build_ipa --verbose
    artifacts:
      - iOS_APP/build/BetBox.ipa
