name: Deploy PWA to GitHub Pages
on:
  push:
    branches: [main]
    paths:
      - 'PWA/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Aggiornato da v2 a v3
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4  # Aggiornato alla v4
        with:
          branch: gh-pages
          folder: PWA
          token: ${{ secrets.DEPLOY_TOKEN }}
