name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: List Xcode versions
      run: |
        ls -l /Applications/ | grep Xcode
        xcode-select -p

    - name: Build
      run: |
        cd iOS_APP
        xcodebuild clean build -project BetBox.xcodeproj -scheme BetBox -destination "platform=iOS Simulator,name=iPhone 14,OS=18.0" -configuration Release
