name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.1_beta.app

    - name: Build and Run Unit Tests
      run: |
        cd iOS_APP
        xcodebuild build-for-testing test -project BetBox.xcodeproj -scheme BetBox -destination "platform=iOS Simulator,name=iPhone 15,OS=18.1" -enableCodeCoverage YES -only-testing:BetBoxTests

  ui-tests:
    needs: build-and-test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.1_beta.app

    - name: Run UI Tests
      run: |
        cd iOS_APP
        xcodebuild test -project BetBox.xcodeproj -scheme BetBox -destination "platform=iOS Simulator,name=iPhone 15,OS=18.1" -only-testing:BetBoxUITests
      timeout-minutes: 20

  archive:
    needs: [build-and-test, ui-tests]
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.1_beta.app

    - name: Archive app
      run: |
        cd iOS_APP
        xcodebuild -project BetBox.xcodeproj -scheme BetBox -sdk iphoneos -configuration Release archive -archivePath $PWD/build/BetBox.xcarchive

    - name: Export .ipa
      run: |
        cd iOS_APP
        xcodebuild -exportArchive -archivePath $PWD/build/BetBox.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build

    - name: Upload .ipa
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: iOS_APP/build/BetBox.ipa
